language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: DfokG9Jp9wXdyCzvF0RWmcISno26SthQgsbjKTd+Yrt4W4R5vw9wqewTQhQ34ma7fJsLQUuGs8B8iUtntqIY7oZPkuAh/vhQHG1X0U3UuqaVUFHaElc8MociTgx8TS6HznlNBW+hc9DD/RPlSC0IfeIYKARyDHBceRRgbOcErDTaZnu4uRJsXcHSxAIlmig+4aTqeBCzmWm/StOfzyb0zX2LH+kb3FOHzkEIshLTELUp+oj4A/1zYEafbJgVMllmqKuYE7AjBREB0z9HAHe/boW9ZK1oS5CVtCdqu78y39SOaef+AP7f1IlFsfGwSb5/2Tra6uOyHvr93G+35ca85Dm3gW4pQP2d8JICWwmsLVVa9c0BZyCLhUNco8Mr5K+amkqYfEQcyc4UENadThS83UlSKXYlvzhcz7nSjXiRXAI0v8zBmFRpMBeWNTcwSXCQyvpJXcn7WvbtwXUHziHR1BXPuTDOosT5leq7iKAIWx0jNltHCjtyO+R3Xj0whgUc9Ywig2esnlBVSNa+bEZVaTHVUxZd4rGFvEZpwSwsvKNpOjF7pmFEtOmBr6s7z8Hq7IAL23qfRUdmxwY8lLRMxhaj6jkC3PBxvsruEhejsVCNJmQmeB7bX+Eb4FWGabl2/MGuLnoTeO1q6t9WooyuHh4QKiyTfh8zYXSsj6bDsX8=
  file:
    - 'remark-slug.js'
    - 'remark-slug.min.js'
  on:
    tags: true
